Add jdk 11 support
frankframework/frankframework pull request #2358
Opened 2021-10-18 08:00 UTC by alisihab

Closes #1998

2021-11-05 08:58 UTC, nielsm5 requested changes

2021-11-05 08:58 UTC, nielsm5 commented on test/pom.xml
> +				<version>3.8.1</version>
Can this be managed via pluginManagement?

2021-11-05 08:58 UTC, nielsm5 commented on test/pom.xml
> +				<version>3.2.2</version>
Can this be managed via pluginManagement?

2021-11-05 08:58 UTC, nielsm5 commented on test/pom.xml
> +		</profile>
I would expect this in the parent pom, and other poms to inherit it from there. Does that not work?

2021-11-05 08:58 UTC, nielsm5 commented on ibm/pom.xml
> +				</dependency>
This doesn't have to be in a profile. You can upgrade the old was6 dependency

2021-11-05 08:58 UTC, nielsm5 commented on core/pom.xml
> +						</exclusion>
Is it possible to exclude these by default? Do we need the JTA spec compile time?

2021-11-10 11:12 UTC, nielsm5 approved these changes

2021-11-10 14:58 UTC, gvanbrakel approved these changes

2021-11-10 14:59 UTC, merged