Use Spring contexts in TX and JDBC based tests
frankframework/frankframework pull request #2850
Opened 2022-03-10 19:46 UTC by nielsm5

When running mvn test:test BTM creates the default tx-log files in the core root directory.
Fixes #2666

2022-03-11 12:18 UTC, gvanbrakel requested changes

2022-03-11 12:18 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/jta/btm/BtmJtaTransactionManagerTest.java
> +		}
Hier is 'BTMXADataSourceFactory.createBtmTransactionManager()' verdwenen. Klopt dat?

2022-03-14 09:41 UTC, gvanbrakel requested changes

2022-03-14 09:41 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/jdbc/JdbcTestBase.java
> +		List<String> datasources;
Type is van DataSource naar String gegaan. Zou je de naam ook aan kunnen passen? Weet nu niet of het 'datasourceNames' of 'productKeys' zijn.

2022-03-14 09:41 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/jdbc/JdbcTestBase.java
> +		assertEquals("DataSourceName does not match", productKey,dataSourceInfo.getProperty(URLDataSourceFactory.PRODUCT_KEY));
productKey en DataSourceName is niet hetzelfde (toch?)

2022-03-14 09:41 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/jdbc/TransactionManagerTestBase.java
>  	public static Collection data() throws NamingException {
Deze code ziet er hetzelfde uit als bij JdbcTestBase. Zouden ze allebei dezelfde codebase kunnen gaan gebruiken?

2022-03-14 09:41 UTC, gvanbrakel commented on core/src/test/java/nl/nn/adapterframework/testutil/TestConfiguration.java
> +		this("testConfigurationContext.xml");
Van deze string ook constant maken, voor de duidelijkheid

2022-03-14 09:41 UTC, gvanbrakel commented on core/src/test/resources/AppConstants.properties
> +transactionmanager.uid=unique
Deze naam kan, maar een iets beschrijvender gaat in een later stadium wel helpen denk ik.

2022-03-14 16:47 UTC, gvanbrakel requested changes

2022-03-14 19:16 UTC, nielsm5 commented on core/src/main/java/nl/nn/adapterframework/jta/btm/BtmJtaTransactionManager.java
> +			return true;
oei, dus niet boolean success? Beetje raar om false terug te geven als het gelukt is?

2022-03-14 19:17 UTC, nielsm5 commented on core/src/test/java/nl/nn/adapterframework/jdbc/TransactionManagerTestBase.java
> +			List<String> productNames;
Vraag je mij eerst er product van te maken en nu datasource, lekker dan

2022-03-15 12:05 UTC, gvanbrakel approved these changes

2022-03-15 17:00 UTC, merged