Use messageWrapper while storing data to database
frankframework/frankframework pull request #2870
Opened 2022-03-15 14:01 UTC by alisihab

Closes #2858

2022-03-17 10:55 UTC, gvanbrakel requested changes

2022-03-17 10:55 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/webcontrol/api/TransactionalStorage.java
> +						}
This change should not be necessary, as messageBrowser returns either MessageWrapper, or M of Listener<M>

2022-03-17 10:55 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/util/MessageBrowsingFilter.java
> +	private String getRawMessageAsText(IMessageBrowser<?> messageBrowser, IListener listener, String messageId) throws IOException, ListenerException {
I would prefer to call this method `getMessageText()`

2022-03-17 14:15 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/webcontrol/api/TransactionalStorage.java
> +				}
Please add a comment that this code is only here to accommodate for a previous version of the code

2022-03-18 07:13 UTC, gvanbrakel approved these changes

2022-03-18 07:15 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/util/MessageBrowsingFilter.java
> +			} else if(rawmsg instanceof Message) { // For backwards compatibility: in case the message is stored as Message and the listener uses a different type.
```suggestion
			} else if(rawmsg instanceof Message) { // For backwards compatibility: earlier MessageLog messages were stored as Message.
```

2022-03-18 07:16 UTC, gvanbrakel commented on core/src/main/java/nl/nn/adapterframework/webcontrol/api/TransactionalStorage.java
> +			} else if(rawmsg instanceof Message) { // For backwards compatibility: in case the message is stored as Message and the listener uses a different type.
```suggestion
			} else if(rawmsg instanceof Message) { // For backwards compatibility: earlier MessageLog messages were stored as Message.
```

2022-03-18 13:26 UTC, nielsm5 approved these changes

2022-03-18 13:56 UTC, merged