Remove more streaming pipes
frankframework/frankframework pull request #5836
Opened 2023-11-22 14:26 UTC by jkosternl

Continue to remove StreamingPipe. Totally removing `StreamingSenderBase` and `MessageOutputStream` needs to wait.

2023-11-22 20:16 UTC, tnleeuw requested changes

2023-11-22 20:16 UTC, tnleeuw commented on core/src/test/java/nl/nn/adapterframework/pipes/JsonXsltPipeTest.java
> +		Assertions.assertEquals(expectedXml, xmlOut);
Can you please fix this imports?

2023-11-23 09:05 UTC, jkosternl commented on core/src/test/java/nl/nn/adapterframework/pipes/JsonXsltPipeTest.java
> +		Assertions.assertEquals(expectedXml, xmlOut);
Yes, didn't intend to do that.

2023-11-23 09:07 UTC, tnleeuw approved these changes

2023-11-23 11:39 UTC, nielsm5 approved these changes

2023-11-23 14:40 UTC, tnleeuw requested changes
Ik weet niet of je hier nog mee bezig bent @jkosternl maar alle CI builds gaan nog mis. Heb je al lokaal de IAF-Test proberen te draaien?

2023-11-23 15:54 UTC, tnleeuw approved these changes

2023-11-23 16:55 UTC, nielsm5 approved these changes

2023-11-23 16:58 UTC, merged