Change to junit5 methods
frankframework/frankframework pull request #6075
Opened 2024-01-07 20:00 UTC by Laurens-makel

2024-01-08 09:18 UTC, jkosternl approved these changes
Hopefully this PR does not double the work Yannick is already doing in my open PRs already. @Laurens-makel, please check his work, if you create more PRs regarding this topic.

2024-01-08 11:25 UTC, tnleeuw requested changes
I don't know how much this doubles with work done by @Yale96  but I see the tests still use JUnit4 `@Test` annotations instead of JUnit5 `@Test` annotations.

Please change those annations as well, otherwise I do not see a lot of point in just changing only the assertions.

2024-01-08 11:25 UTC, tnleeuw commented on core/src/test/java/org/frankframework/statistics/StatisticsKeeperTest.java
> +		assertEquals(null, sk.getIntervalItemValue(3), sk.getIntervalItemName(3)); // avg
What about using `assertNull()`?

2024-01-08 11:25 UTC, tnleeuw commented on core/src/test/java/org/frankframework/util/LockerTest.java
>  import static org.junit.Assume.assumeFalse;
Still using the JUnit4 `assumeFalse()` method and Hamcrest Matchers that are JUnit4 compatible.
However I'm aware by now that this is not a simple change.

2024-01-11 20:52 UTC, Laurens-makel commented
Thanks for the review.

I'm planning to work on the feedback in the next couple of days. If a problem arises with the Hamcrest Matchers, I think I'll keep it out of scope for this PR since this was meant as a quick & easy win.

2024-01-11 21:09 UTC, tnleeuw commented
> Thanks for the review.
> 
> I'm planning to work on the feedback in the next couple of days. If a problem arises with the Hamcrest Matchers, I think I'll keep it out of scope for this PR since this was meant as a quick & easy win.

That's fine, I just wanted to highlight it!

2024-02-01 17:06 UTC, closed without merging