Convert MessageStoreListenerTest
frankframework/frankframework pull request #6193
Opened 2024-01-30 18:59 UTC by nielsm5

2024-01-31 14:16 UTC, tnleeuw requested changes

2024-01-31 14:16 UTC, tnleeuw commented on core/src/test/java/org/frankframework/jdbc/MessageStoreListenerTest.java
> +import static org.junit.Assume.assumeTrue;
Dit zijn nog allemaal JUnit4 methods.

2024-01-31 14:56 UTC, nielsm5 commented on core/src/test/java/org/frankframework/jdbc/MessageStoreListenerTest.java
> +import static org.junit.Assume.assumeTrue;
Grrr...

2024-01-31 15:26 UTC, tnleeuw commented on core/src/test/java/org/frankframework/jdbc/MessageStoreListenerTest.java
> +		assumeTrue(Dbms.H2 == env.getDbmsSupport().getDbms()); // tests are based on H2 syntax queries
So the tests are only executed for H2 and for all other databases they are skipped? Is that right actually, that we will never test against other databases when they're running?

2024-02-01 09:14 UTC, jkosternl approved these changes

2024-02-01 09:20 UTC, merged