Update Angular to v17
frankframework/frankframework pull request #6359
Opened 2024-02-26 16:23 UTC by Matthbo

Updates Angular from v15 to v17

2024-02-26 17:32 UTC, philipsens approved these changes

2024-02-26 17:34 UTC, philipsens requested changes
Can you change the nodejs version in the GitHub Actions?

2024-02-26 17:36 UTC, Matthbo commented
@philipsens yeah gotta update the pom too, im home soon so I'll fix it after I had dinner ;)

2024-02-27 08:33 UTC, philipsens approved these changes

2024-02-27 10:10 UTC, merged