Merge IExtendedPipe into IPipe
frankframework/frankframework pull request #6366
Opened 2024-02-27 11:57 UTC by jkosternl

2024-02-27 13:01 UTC, tnleeuw commented on core/src/main/java/org/frankframework/processors/MonitoringPipeProcessor.java
> +			if (pipe!=null) {
Zou `pipe` ooit `null` kunnen zijn in `processPipe()`?

Ik zie dat er al null-checks op `pipe` inzitten maar dat is absoluut onlogisch.

Ook `pipeLineSession` zou nooit `null` mogen kunnen zijn in deze code, daar zie ik ook `null` checks op.
Andere PipeProcessor implementaties hebben die null-checks op pipe en pipeLineSession ook niet en ze zijn allemaal genest -- haal die null-checks maar weg hier!

2024-02-28 15:06 UTC, tnleeuw commented on core/src/main/java/org/frankframework/processors/MonitoringPipeProcessor.java
> +	protected PipeRunResult processPipe(PipeLine pipeLine, @Nonnull IPipe pipe, Message message, @Nonnull PipeLineSession pipeLineSession, ThrowingFunction<Message, PipeRunResult, PipeRunException> chai
Nu we die annotaties hier zetten moeten we misschien dat maar gelijk uitbreiden naar de interface zelf (en dus ook naar de andere implementaties?)

Just a suggestion.

2024-02-28 16:08 UTC, tnleeuw requested changes

2024-02-28 16:08 UTC, tnleeuw commented on core/src/main/java/org/frankframework/processors/PipeProcessor.java
> +	PipeRunResult validate(@Nonnull PipeLine pipeLine, @Nonnull IValidator validator, Message message, @Nonnull PipeLineSession pipeLineSession, String messageRoot) throws PipeRunException;
Hier nog `@Nullable` toevoegen aan het `message` argument?

2024-02-28 16:19 UTC, jkosternl commented on core/src/main/java/org/frankframework/processors/PipeProcessor.java
> +	PipeRunResult validate(@Nonnull PipeLine pipeLine, @Nonnull IValidator validator, Message message, @Nonnull PipeLineSession pipeLineSession, String messageRoot) throws PipeRunException;
Euh ja, die had ik nog gemist. Tevens nog een paar andere classes nu uitgevoerd.

2024-02-28 16:21 UTC, tnleeuw approved these changes

2024-03-01 17:21 UTC, nielsm5 approved these changes

2024-03-01 17:21 UTC, merged