Add Kubernetes Module and CredentialFactory
frankframework/frankframework pull request #6521
Opened 2024-03-26 16:11 UTC by jkosternl

Also bumped 2 deps.

2024-03-27 13:57 UTC, jkosternl commented on kubernetes/src/main/java/org/frankframework/credentialprovider/KubernetesCredentialFactory.java
> +				.findFirst().orElse(null);
Hierboven staat de code om met een alias een Credential te vinden en terug te geven. Deze code, vanaf regel 98 gaat over het matchen op username & password. Dan moet ik wel filteren.

2024-03-27 14:02 UTC, jkosternl commented on kubernetes/src/test/java/org/frankframework/credentialprovider/KubernetesCredentialFactoryTest.java
> +		assertEquals("testPassword1", credential2.getPassword());
Goed punt. Zal daar nog wat testen voor toevoegen.

2024-03-27 15:20 UTC, nielsm5 commented on kubernetes/src/main/java/org/frankframework/credentialprovider/KubernetesCredentialFactory.java
> +				.findFirst().orElse(null);
Waarom zou je iets moeten matchen? Je moet direct de fallback / defaults teruggeven?

2024-03-27 16:04 UTC, jkosternl commented on kubernetes/src/main/java/org/frankframework/credentialprovider/KubernetesCredentialFactory.java
> +				.findFirst().orElse(null);
Ik had blijkbaar functioneel niet hetzelfde beeld in mijn hoofd. Aangepast.

2024-03-27 17:16 UTC, nielsm5 approved these changes

2024-03-27 17:18 UTC, nielsm5 commented on kubernetes/src/test/java/org/frankframework/credentialprovider/KubernetesCredentialFactoryTest.java
> +		ICredentials credential1 = credentialFactory.getCredentials("alias1", () -> "testUsername1", () -> "testPassword1");
```suggestion
		ICredentials credential1 = credentialFactory.getCredentials("alias1", () -> "testUsername", () -> "testPassword");
```

2024-03-27 20:38 UTC, nielsm5 commented on kubernetes/src/test/java/org/frankframework/credentialprovider/KubernetesCredentialFactoryTest.java
> +		assertThrows(NoSuchElementException.class, () -> credentialFactory.getCredentials(null, null, () -> "testPassword2"));
Hier zou ik geen fouten verwachten.

2024-03-27 20:41 UTC, nielsm5 requested changes
Je kan een wachtwoord hebben zonder username. Bij jou gaat dit nu fout, kan je niet beter de Credentials class gebruiken?

2024-03-28 08:39 UTC, jkosternl commented on kubernetes/src/test/java/org/frankframework/credentialprovider/KubernetesCredentialFactoryTest.java
> +		assertThrows(NoSuchElementException.class, () -> credentialFactory.getCredentials(null, null, () -> "testPassword2"));
Opgelost.

2024-03-28 09:09 UTC, nielsm5 approved these changes

2024-03-28 10:17 UTC, merged