Increase max log file size to 10MB by default; increase message persist to disk size
frankframework/frankframework pull request #6598
Opened 2024-04-05 09:33 UTC by jkosternl

Info: The current defaults are outdated. Sergi experienced already the disadvantage of the current settings, to lose important log files. 10MB is a better default, which is easy to load in text editors or other tools. 

Since heap sizes are not 256MB anymore nowadays, it is a good idea to move to 2MB message to persist to disk, instead of 512KB. This increases performance, since disks are slow and memory is fast (and GC algorithms are fast and parallel as well).

Summary:
- Increase max log file size to 10MB by default; 
- increase message persist to disk size

2024-04-05 10:54 UTC, nielsm5 commented
Increasing message persistence to disk is ok, I think even 5 mb is reasonable. However the log files configuration should not change. Whoever has told you they are having rollover problems should either set these properties them selves or turn of DEBUG logging in a containerized environment (use at least INFO !).

2024-04-05 10:58 UTC, jkosternl commented
> Increasing message persistence to disk is ok, I think even 5 mb is reasonable. However the log files configuration should not change. Whoever has told you they are having rollover problems should either set these properties them selves or turn of DEBUG logging in a containerized environment (use at least INFO !).

Sure, I'll make the persistence limit 5MB.

Nobody told me there are problems with rolling log files. But in this decade, it is no issue to transfer, open, search in log files of 10MB. And if something happens (errors & stacktraces) the logs rotates too fast and you will lose important information. Even when you have configured the log level at INFO.

2024-04-08 14:02 UTC, nielsm5 requested changes

2024-04-08 14:02 UTC, nielsm5 commented on core/src/main/resources/AppConstants.properties
> +#   ibistesttool.maxFileSize=10MB
Deze dus terug

2024-04-08 14:02 UTC, nielsm5 commented on core/src/main/resources/log4j4ibis.properties
>  log.msg.maxBackupIndex=9
de xml size mag weg, en ik denk toch dat het beter is om hem op 1MB te laten.
In de FrankLogConfigurationFactory#setLevel kan de default naar INFO

2024-04-08 16:29 UTC, jkosternl commented on core/src/test/java/org/frankframework/logging/FrankLogConfigurationFactoryTest.java
> +		properties.setProperty("log.maxFileSize", "10MB");
Klopt. Had het overal hetzelfde gemaakt, qua consistentie.

2024-04-09 07:44 UTC, jkosternl commented on ladybug/src/main/resources/log4j4testtool.properties
> +log4j.appender.TestToolRollingFileAppender.MaxFileSize=10MB
Oke, zet ik terug.

2024-04-09 08:17 UTC, jkosternl commented on core/src/test/resources/log4j4ibis.properties
>  log.xml.maxBackupIndex=9
Oke, haal ik weg.

2024-04-10 11:06 UTC, nielsm5 approved these changes

2024-04-10 11:06 UTC, merged