Allow custom headers in CMIS
frankframework/frankframework pull request #6620
Opened 2024-04-09 08:58 UTC by nielsm5

2024-04-09 11:01 UTC, tnleeuw commented on cmis/src/main/java/org/frankframework/extensions/cmis/CmisSender.java
> +				for(Entry<String, Object> entry : pvl.getValueMap().entrySet()) {
De `ParameterValue` class die in the `ParameterValueList` zit kan ook de parameter value al als string terug geven, waarom gebruik je die eigenlijk niet?

2024-04-09 11:04 UTC, tnleeuw requested changes
We moeten iets met `username` vs `userName` spelling in the parameters, nu dat we niet meer allebei ondersteunen maar in de `configure()` wel nog op beide een check doen.
Misschien dat we in `configure()` een check moeten doen dat de oude naam niet meer mag worden geconfigured? En de oude spelling weghalen uit de checks voor `runtimeSession`.

2024-04-09 12:35 UTC, tnleeuw approved these changes

2024-04-10 08:11 UTC, jkosternl approved these changes

2024-04-10 11:52 UTC, merged