Backport param substitution
frankframework/frankframework pull request #6790
Opened 2024-05-07 13:20 UTC by nielsm5

2024-05-07 15:21 UTC, tnleeuw approved these changes

2024-05-08 08:23 UTC, jkosternl requested changes
Still a few `$` found.

2024-05-08 09:04 UTC, nielsm5 commented on core/src/main/java/org/frankframework/pipes/FixedResultPipe.java
>   * no <code>${...}</code> patterns are left if the initial string came from attribute <code>returnString</code>, because
It's meant to be there.

2024-05-08 09:06 UTC, jkosternl commented on core/src/main/java/org/frankframework/pipes/FixedResultPipe.java
>   * no <code>${...}</code> patterns are left if the initial string came from attribute <code>returnString</code>, because
Ok

2024-05-08 09:13 UTC, jkosternl approved these changes

2024-05-08 10:16 UTC, nielsm5 commented on core/src/main/java/org/frankframework/pipes/FixedResultPipe.java
>  	 * Should values between ${ and } be resolved. If true, the search order of replacement values is:
SubstituteVars works with properties, not with parameters

2024-05-08 13:26 UTC, merged