Enable Ladybug
frankframework/frankframework pull request #6876
Opened 2024-05-27 08:16 UTC by jacodg

2024-05-27 08:59 UTC, tnleeuw commented
There are errors starting the Ladybug, see: https://jenkins.frankframework.org/job/ff-ci/job/larva/36528/

From the logs:

```
2024-05-27 10:39:27,286 INFO  [main] {} APPLICATION - Successfully started Frank EnvironmentContext
2024-05-27 10:39:27,286 DEBUG [main] {} APPLICATION - Starting Ladybug TestTool
2024-05-27 10:39:27,312 INFO  [main] {} APPLICATION - loading TestTool configuration [classpath:springIbisTestTool.xml]
2024-05-27 10:39:28,237 DEBUG [main] {} servlets.ServletConfiguration - converted raw mapping [/iaf/ladybug/api/*] to [/iaf/ladybug/api/*]
2024-05-27 10:39:28,237 INFO  [main] {} servlets.NoOpAuthenticator - registering private endpoint with url pattern [/iaf/ladybug/api/*]
2024-05-27 10:39:28,238 DEBUG [main] {} servlets.ServletConfiguration - converted raw mapping [/iaf/ladybug/*] to [/iaf/ladybug/*]
2024-05-27 10:39:28,238 INFO  [main] {} servlets.NoOpAuthenticator - registering private endpoint with url pattern [/iaf/ladybug/*]
2024-05-27 10:39:28,239 DEBUG [main] {} servlets.ServletConfiguration - converted raw mapping [/iaf/testtool] to [/iaf/testtool]
2024-05-27 10:39:28,239 INFO  [main] {} servlets.NoOpAuthenticator - registering private endpoint with url pattern [/iaf/testtool]
2024-05-27 10:39:28,299 FATAL [main] {} APPLICATION - Unable to start Ladybug TestTool
org.springframework.context.ApplicationContextException: Unable to start web server
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:165) ~[spring-boot-3.3.0.jar:3.3.0]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:618) ~[spring-context-6.1.8.jar:6.1.8]

...
Caused by: java.lang.IllegalStateException: Failed to register 'filter springSecurityFilterChain' on the servlet context. Possibly already registered?
	at org.springframework.boot.web.servlet.DynamicRegistrationBean.register(DynamicRegistrationBean.java:122) ~[spring-boot-3.3.0.jar:3.3.0]
	at org.springframework.boot.web.servlet.RegistrationBean.onStartup(RegistrationBean.java:52) ~[spring-boot-3.3.0.jar:3.3.0]

```

2024-05-27 17:42 UTC, jacodg commented
Sorry, when creating the PR I overlooked that I had locally disabled SecurityFilterChainConfigurer to prevent this error while looking into other errors. I hope Niels can fix this error

2024-05-28 07:31 UTC, tnleeuw requested changes
Ladybug doesn't start, blocking framework startup. Needs to be fixed before this can be merged.

2024-05-29 10:11 UTC, nielsm5 commented on ladybug/src/main/java/org/frankframework/ibistesttool/tibet2/Storage.java
> +//		String rowNumber = dbmsSupport.getRowNumber(metadataNames.get(0), "desc");
I've created issue #6900 in order to fix this!

2024-05-29 10:12 UTC, nielsm5 commented on ladybug/src/main/resources/springIbisTestTool.xml
> +		<!-- constructor-arg value="${ladybug.jdbc.datasource:${jdbc.datasource.default}}"/ -->
I've created issue #6901 to re-enable this.

2024-05-29 10:13 UTC, nielsm5 approved these changes

2024-05-29 10:18 UTC, tnleeuw commented on ladybug/src/main/java/org/frankframework/ibistesttool/jdbc/LadyBugDataSourceFactory.java
> +//		if (isPooledDataSource(dataSource)) {
Zullen we alle uit-gecommentariseerde code er maar gelijk uithalen?

2024-05-29 10:18 UTC, tnleeuw commented on ladybug/src/main/resources/springIbisTestTool.xml
> +		<!-- constructor-arg value="${ladybug.jdbc.datasource:${jdbc.datasource.default}}"/ -->
Datasource name moet leeg blijven?

2024-05-29 11:21 UTC, nielsm5 commented on ladybug/src/main/resources/springIbisTestTool.xml
> +		<!-- constructor-arg value="${ladybug.jdbc.datasource:${jdbc.datasource.default}}"/ -->
[Ja zie mijn bovenstaande comment](https://github.com/frankframework/frankframework/pull/6876#discussion_r1618628457)

2024-05-29 19:39 UTC, tnleeuw approved these changes

2024-05-30 08:03 UTC, merged