Add CSRF handling to Spring MVC & Angular
frankframework/frankframework pull request #6925
Opened 2024-05-31 13:57 UTC by Matthbo

2024-05-31 13:58 UTC, nielsm5 commented on console/war/src/main/java/org/frankframework/web/RegisterServletEndpoints.java
> +
Ik heb in #6924 opgelost dat dit niet meer hoeft :)

2024-05-31 15:11 UTC, nielsm5 commented on console/backend/src/main/java/org/frankframework/web/filters/DynamicFilterConfigurer.java
> +		CSRF_COOKIE_FILTER(CsrfCookieFilter.class, "/iaf/api/*");
```suggestion
		CSRF_COOKIE_FILTER(CsrfCookieFilter.class, "/iaf/gui/*");
```

2024-06-03 15:31 UTC, nielsm5 commented on console/backend/src/main/java/org/frankframework/web/filters/CsrfCookieFilter.java
> +		csrfToken.getToken();
```suggestion
		csrfToken.getToken(); //Required to retrieve the cookie and store it in the HttpSession.
```

2024-06-03 16:13 UTC, Matthbo commented on security/src/main/java/org/frankframework/lifecycle/servlets/ServletAuthenticatorBase.java
> +				CookieCsrfTokenRepository csrfTokenRepository = CookieCsrfTokenRepository.withHttpOnlyFalse();
Ja die is verplicht

2024-06-03 17:41 UTC, Matthbo commented on security/src/main/java/org/frankframework/lifecycle/servlets/ServletAuthenticatorBase.java
> +				CookieCsrfTokenRepository csrfTokenRepository = CookieCsrfTokenRepository.withHttpOnlyFalse();
Wacht nee ik las het verkeerd, vgm kan die wel aan staan

2024-06-03 18:39 UTC, nielsm5 requested changes

2024-06-03 18:39 UTC, nielsm5 commented on security/src/main/java/org/frankframework/lifecycle/servlets/ServletAuthenticatorBase.java
> +				http.csrf((csrf) -> csrf
Haakjes kunnen weg

2024-06-03 18:39 UTC, nielsm5 commented on security/src/main/java/org/frankframework/lifecycle/servlets/ServletAuthenticatorBase.java
> +				if(StringUtils.isEmpty(csrfCookiePath)) {
Als leeg dan... zetten?

2024-06-03 19:11 UTC, nielsm5 approved these changes

2024-06-03 20:37 UTC, merged