Pipe/Validator related refactoring and code-cleanup
frankframework/frankframework pull request #7008
Opened 2024-06-17 11:00 UTC by tnleeuw

2024-06-17 14:36 UTC, tnleeuw commented on core/src/main/java/org/frankframework/core/IPipe.java
> +	 * so one pipe affects all pipes in the pipeline (and multiple values in different pipes are merged)
It's copy-paste of existing JavaDoc from AbstractPipe so I did not review it for clarity... I'll rephrase that a bit.

Regarding full or partial match: should be partial match as it matches against log lines. Again, I'll double-check that code and clarify in the JavaDoc!

2024-06-17 14:38 UTC, tnleeuw commented on core/src/main/java/org/frankframework/pipes/XmlValidator.java
> +	public static class ResponseValidatorWrapper extends AbstractResponseValidatorWrapper<XmlValidator> implements IXmlValidator {
There's also one in the BaseResponseValidator. They were duplicating all the delegating-logic.

2024-06-17 17:58 UTC, tnleeuw commented on core/src/main/java/org/frankframework/core/IPipe.java
> +	 * so one pipe affects all pipes in the pipeline (and multiple values in different pipes are merged)
I hope that the updated JavaDoc covers what was unclear to you.

2024-06-17 18:34 UTC, jkosternl commented on core/src/main/java/org/frankframework/pipes/XmlValidator.java
> +	public static class ResponseValidatorWrapper extends AbstractResponseValidatorWrapper<XmlValidator> implements IXmlValidator {
Ah yes, I was looking at the right side of the diff. No I see it. Great.

2024-06-17 18:36 UTC, jkosternl commented on core/src/main/java/org/frankframework/core/IPipe.java
> +	 * so one pipe affects all pipes in the pipeline (and multiple values in different pipes are merged)
Yes, much better. Thanks!

2024-06-17 18:36 UTC, jkosternl approved these changes

2024-06-17 18:38 UTC, tnleeuw commented on core/src/main/java/org/frankframework/core/IPipe.java
> +	 * so one pipe affects all pipes in the pipeline (and multiple values in different pipes are merged)
You're welcome!

2024-06-19 13:25 UTC, evandongen requested changes

2024-06-19 13:25 UTC, evandongen commented on core/src/main/java/org/frankframework/core/Adapter.java
> +		if ("()".equals(combinedHideRegex)) return "";
Kwestie van stijl denk ik - maar ik zou dit voor de leesbaarheid uitschrijven:

```suggestion
		if ("()".equals(combinedHideRegex)) {
			return "";
		}
```

2024-06-19 13:25 UTC, evandongen commented on core/src/main/java/org/frankframework/processors/MonitoringPipeProcessor.java
> +				durationLog.info("Pipe [{}] of [{}] duration [{}] ms exceeds max [{}], message [{}]", pipe::getName, ()->pipeLine.getOwner().getName(), ()->pipeDuration, pipe::getDurationThreshold, ()->message);
```suggestion
				durationLog.info("Pipe [{}] of [{}] duration [{}] ms exceeds max [{}], message [{}]", pipe::getName, () -> pipeLine.getOwner().getName(), () -> pipeDuration, pipe::getDurationThreshold, () -> message);
```

2024-06-19 13:31 UTC, jkosternl commented on core/src/main/java/org/frankframework/core/IPipe.java
> +	 * so one pipe affects all pipes in the pipeline (and multiple values in different pipes are merged)
Ik fix het wel met de hand.

2024-06-19 13:35 UTC, evandongen approved these changes

2024-06-19 14:08 UTC, merged