Remove Message.asByteArray
frankframework/frankframework pull request #7066
Opened 2024-06-25 09:52 UTC by evandongen

As discussed with Tim, I try to split this up in different pull requests, to make it managable. This removes the static Message.asByteArray.

2024-06-25 10:19 UTC, nielsm5 approved these changes

2024-06-25 15:13 UTC, tnleeuw requested changes

2024-06-25 15:13 UTC, tnleeuw commented on core/src/test/java/org/frankframework/stream/MessageTest.java
> +		byte[] byteArray = testString.getBytes();
What are you testing here in these 2 tests?

They were testing the `Message.asByteArray(source)` but that method is removed. Now there's really nothing left in this test.

2024-06-27 06:55 UTC, tnleeuw approved these changes

2024-06-27 08:09 UTC, merged