Parameterize all logging statements
frankframework/frankframework pull request #7073
Opened 2024-06-25 15:45 UTC by jkosternl

Sonar 2.1k maintainability issue fixes!

2024-06-26 13:02 UTC, nielsm5 requested changes

2024-06-26 14:44 UTC, jkosternl commented on core/src/main/java/org/frankframework/jdbc/JdbcTransactionalStorage.java
>  		}
GitHub weigert te werken met een commit suggestion in verwijderde regels, lijkt het. Iig gooi ik dit debug-blok wel effe met de hand weg idd.

2024-06-27 07:13 UTC, jkosternl commented on core/src/main/java/org/frankframework/align/XmlTypeToJsonSchemaConverter.java
> +		if (log.isTraceEnabled()) log.trace("typeDefinition.name [{}]", typeDefinition.getName());
Ja uiteraard. Ik neem dit nog mee. 
Het doel van deze PR is om die parameters te fixen... ik wil niet allerlei extra dingen blijven doen, want dan kan deze gemergd worden. Andere fixes kunnen altijd nog in een volgende PR 😉

2024-06-27 07:31 UTC, nielsm5 approved these changes

2024-06-27 08:10 UTC, merged