Show a console warning when the XmlValidator pipe is in an incorrect state.
frankframework/frankframework pull request #7284
Opened 2024-08-08 09:43 UTC by thomaspj10

Closes #6800

2024-08-08 13:57 UTC, nielsm5 requested changes

2024-08-08 13:57 UTC, nielsm5 commented on core/src/test/java/org/frankframework/pipes/XmlValidatorPipelineTest.java
> +		assertWarnings(configuration, 1);
I saw in `buildXmlValidator(...)` a method call `createFailureForward()` perhaps you could remove that line, and make a specific test when adding it, that you will see 1 warning opposed to 0 😃

2024-08-08 14:54 UTC, nielsm5 approved these changes
Ik snap hem helemaal! Misschien dat het verschil tussen de tests met throwException en useFailureForward iets explicieter kunnen (in de test het aanzetten ipv uitzetten van de tegenhanger). Maar verder prima!

2024-08-12 06:43 UTC, evandongen approved these changes

2024-08-12 08:47 UTC, merged