Added messagesReceiving and messagesPeeking to the receiver map
frankframework/frankframework pull request #7415
Opened 2024-08-29 13:54 UTC by evandongen

Ik ben onderweg, maar nog in afwachting van https://github.com/frankframework/frankframework/pull/7396#top voordat ik dit kan afronden

2024-09-03 07:16 UTC, evandongen commented on core/src/main/java/org/frankframework/metrics/LocalStatisticsRegistry.java
> +	private JsonObjectBuilder getHttpStatistics(Collection<Meter> adapterScopedMeters) {
Dit resulteert uiteindelijk in een blok JSON wat er ongeveer zo uit ziet:

```
    "http": {
        "connections": {
            "max": 10.0,
            "available": 0.0,
            "leased": 0.0,
            "pending": 0.0
        },
        "timers": [
            {
                "uri": "/iaf-test/api/exception",
                "timers": [
                    {
                        "hostname": "laptop-erik",
                        "instance": "Ibis4Test",
                        "method": "POST",
                        "outcome": "REDIRECTION",
                        "status": "304",
                        "target_host": "localhost",
                        "target_port": "8080",
                        "target_schema": "http",
                        "count": 1,
                        "total": 0.0021063,
                        "max": 0.0
                    },
                    {
                        "hostname": "laptop-erik",
                        "instance": "Ibis4Test",
                        "method": "POST",
                        "outcome": "SERVER_ERROR",
                        "status": "500",
                        "target_host": "localhost",
                        "target_port": "8080",
                        "target_schema": "http",
                        "count": 1,
                        "total": 0.0290868,
                        "max": 0.0
                    }
                ]
            },
		...
        ]
    },
```

2024-09-04 13:08 UTC, nielsm5 requested changes

2024-09-04 13:08 UTC, nielsm5 commented on core/src/main/java/org/frankframework/metrics/LocalStatisticsRegistry.java
> +	}
een receiver kan maar 1 listener hebben. Deze extra array hoeft dus niet.

2024-09-05 07:57 UTC, nielsm5 commented on core/src/main/java/org/frankframework/metrics/LocalStatisticsRegistry.java
> +		List<LocalDistributionSummary> summaryListPeeking = getDistributionSummaryList(meters, FrankMeterType.LISTENER_MESSAGE_PEEKING);
Kan je niet gewoon `getDistributionSummary(Collection<Meter> meters, FrankMeterType type)` gebruiken?

2024-09-05 09:09 UTC, evandongen commented on core/src/main/java/org/frankframework/metrics/LocalStatisticsRegistry.java
> +		List<LocalDistributionSummary> summaryListPeeking = getDistributionSummaryList(meters, FrankMeterType.LISTENER_MESSAGE_PEEKING);
Dat gaat helaas niet werken, op dit punt heb ik er bijvoorbeeld 2 voor 1 adapter (JDBCTableListener en JDBCQueryListener). De methode die jij noemt kan daar niet mee omgaan, die doet: `throw new IllegalStateException("found more then 1 "+type+" statistic")` indien er meer dan 1 wordt gevonden.

2024-09-05 13:09 UTC, nielsm5 approved these changes

2024-09-05 13:09 UTC, merged